replicaCount: 1

image:
  repository: ghcr.io/dirdr/utazon-backend
  tag: "sha-7728660"  # auto-updated by CI
  pullPolicy: Always

service:
  port: 3001

ingress:
  host: api.utazon.fr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

env:
  RUST_LOG: "utazon_backend=info,tower_http=info,tower=warn"
  ALLOWED_ORIGINS: "https://utazon.fr,*.pages.dev"
