---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-stalwart-env
  namespace: stalwart
spec:
  encryptedData:
    STALWART_RECOVERY_ADMIN: AgAslNdOMeVlUXy55M1WrMSvPb4Z9jJ8caIx5zhCH4cRF4fneaaVIHGTJFgBPaXmmlCWgF+P1WHEnaw6ZUQ2hkDXm8Bw0tqhSAAHeBZS6/x4PbezjmCQiJfU5Vh2m/VnKup2D1X4vzxksUQ2uqHn6OD9WFxGzsorzfhXz0T9oySWCJo9JJ5JKI7J4jUxsT+9abH3d63epVuA75SgUD0JBknVZaUXriQAeZx25OFjAv3TY500FdfmcS74UV+TPGTEX5/koElOEQldcyJ6lCXHEoKkJ2+kVEbNPD+QmstxE/pYskiQT65a89VtiX5oY7Byu8/IkaszOIUhiX29swJhdxQw5Dk16xIDJLeGbJHgGTtgdw1KrIOyVpKAWyrhipNXbXl2eS9Fi7mBBA3XXEIclevP78C4wTJmBBQrwSNo//jGPEdwal4xQMgBfRRTxVdLP3lLEWTOXY5jKqLYu/LuyH4zsAWZjFjVFp1AGawKx1R6WOWVw1ey2RIN+MjkxHphKJbyP6hFIl4tgG+F155YtGc9HjdY+XkdDQFJStwiH56VmVa4CggcCQjVRWBNRFnd2CRecNDPQRzI/F19kDF3YbLlZbQFvQWEUTN0rw07M6M5X1L8ghzd5Kmp/DlhXxbxTkjqMd5oGvDO1yDaqXNn5lUsx3yTJNwtE2Ny4WhGX9pmpmq60S2jgJYoNS9oY1LDO4hnhlQ7DvxJG/IESZzo6RJrybH08CPbgcbVa0x8jnaqkdh2zz21iQ==
  template:
    metadata:
      name: stalwart-stalwart-env
      namespace: stalwart
