controller:
  type: daemonset

alloy:
  configMap:
    content: |
      discovery.kubernetes "pods" {
        role = "pod"
        namespaces {
          names = ["utazon"]
        }
      }

      discovery.relabel "utazon_logs" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_pod_phase"]
          regex         = "Succeeded|Failed"
          action        = "drop"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label  = "__host__"
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
      }

      loki.source.kubernetes "utazon" {
        targets    = discovery.relabel.utazon_logs.output
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
