---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-cloudflare-token
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBOff2x3Gkpe79Tst9HP3po+H+oMb/3BY/j8NrwbpZHpmG+CPIO63tif7efP/iQgpV1UuuW8wCSWu0B6vAKVoDmV8F2jSGPwLtdkId/SmrEH/Z8U+QBtRLwxFCBuau51/yNIYY5t4iJ6pcC2TPPhnot9FcJn9TIY94iIV50O/LZax5l8n8zOXuv9cCHsnpjbv1NU7FTLltMwomdjgF5ZAJOSLEzFxYpGieyiSAmTEGkTy3kFnzga5Yc1gsPp5NLak5Dc7YPIMaAHkHNWwlBNeWo5S+hTxhuVzYhag37M3hiMRE8O6c7ZSE+X+DmdYYuqkvpRJ42BB6vGLwwwIXUoHa9EOZsTv1xxROxyZemIlFDzKV4kEx5DHbOJTNmGt+D+qYpuZ443y2kvgLYjqv6xi9O7gTCoFtHoAB47faIoulCJsRocUOsEEHFKjgIXrwQVLNm7GAkcm9fbzwWQi/mf6HiIk25qapV5xVX8p13QuWXyCaF5jTWJNDpJRr+HkM6Q9tykgv0w53Ezy80aM+ysGu0bmsulYUnpwGmk7DLURuxlPJA1uy/lU1o3FYJmla9HES7ipdyIOzDwFfesan5yIzABtqMYZFDVlIfm2LVJ+SF2V64VNFqf84i4TeTS6edan+OPUnnqz5W1eLwSrBZvpK1UhI0SgBWokG+OsAk6/y8NMi4n3Ldwb1RSP9gp4f/RBfGnpHpL5Sb1BlrtmBsydcJIu+x8PkE8ZR0ixNrKJ4jsv4CfJfXd54JkgfxBeNmJzKIBa02Xg==
  template:
    metadata:
      name: traefik-cloudflare-token
      namespace: kube-system
