apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
              priority: 10
    certificatesResolvers:
      letsencrypt:
        acme:
          email: {{ .Values.acme.email }}
          caServer: {{ .Values.acme.caServer }}
          storage: {{ .Values.acme.storage }}
          httpChallenge:
            entryPoint: web
