apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stalwart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dirdr/adrien_kubernetes_cluster
    targetRevision: main
    path: stalwart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stalwart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
