configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.adrienpelfresne.com
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    tls: false
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 256Mi

controller:
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 2Gi

repoServer:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 256Mi

notifications:
  enabled: false
